name: Build acme docker image on Perlmutter login node

on:
  #schedule:
  #  - cron: "0 5 * * 2"

  workflow_dispatch:

jobs:

  push_to_registries:
    name: Push Docker image to multiple registries
    runs-on: pm-login
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        with:
          repository: dingp/acme
          path: acme
      
      - name: prepare build dir and build with podman-hpc
        run: |
          build_dir="${{ github.workspace }}/docker-build"
          mkdir -p $build_dir
          cd $build_dir
          cp ${{ github.workspace }}/acme/Dockerfile $build_dir
          cp ${{ github.workspace }}/acme/*.sh $build_dir
          podman-hpc build -t ghcr.io/dingp/acme:latest -f Dockerfile .

          #- name: Log in to the Container registry and push the image
          #run: |
          #podman-hpc login -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
          #podman-hpc push ghcr.io/dingp/acme:latest
      
